### ISSUE TITLE
Empty window with latest vulkan-api and easytensor

### ISSUE THREAD

**Issue by cjay** [cjay/vulkyrie#1]
@achirkin do you have any idea what could be wrong here? I upgraded to the latest vulkan-api and easytensor and ported over your changes from `vulkan-triangles`. I can't figure out what's wrong. It worked fine with the previous versions. It should display two rotating squares with different textures, but the window just shows the clearing color now.

The current `vulkan-triangles` does work as it should though.

Btw the vulkan-api version constraint of easytensor-vulkan-1.0.1.0 (the old version) is too permissive (vulkan-api >=1.1.3.1), it doesn't work with vulkan-api-1.2.0.0.

**Comment by achirkin** [comment]
Sorry, I forgot to tell you that the matrix layout was transposed in `easytensor`-v2. Here is a list of the most important changes: [easytensor#what-have-changed-since-version-1](https://github.com/achirkin/easytensor#what-have-changed-since-version-1).

The result is that now you need to apply transformation matrices on the right of a vector;
i.e. if you want to apply a series of transformations, you need to multiply matrices from left to right. I've noticed three matrix products in your project; just flipping the order of matrices in the products does the trick.

Note, however, SPIR-v and GLSL still perceives matrices as column-major by default. Thus, all matrices appear transposed in your shaders. Thus, you don't need to flip multiplications there - just leave them as is.

**Comment by cjay** [comment]
Thanks, I should have looked for release notes :)
